import { beforeAll } from 'vitest'

process.env.NODE_ENV = 'test'
process.env.JWT_SECRET = 'fluow-test-jwt-secret-not-for-production'
process.env.INTERNAL_API_KEY = 'fluow-test-internal-key'
process.env.CREDENTIAL_ENCRYPTION_KEY = 'fluow-test-credential-encryption-key-32chars'
process.env.DATABASE_URL = 'postgresql://postgres:postgres@localhost:5432/fluow_control_test'
process.env.REDIS_URL = 'redis://localhost:6379'
process.env.SUPABASE_URL = 'http://localhost:8000'
process.env.SUPABASE_SERVICE_KEY = 'test-supabase-key'
process.env.MINIO_ACCESS_KEY = 'test-minio'
process.env.MINIO_SECRET_KEY = 'test-minio-secret'
process.env.MINIO_ENDPOINT = 'localhost'
process.env.MINIO_PORT = '9000'
process.env.MINIO_USE_SSL = 'false'
process.env.FLUOW_AGENT_URL = 'http://localhost:3001'
process.env.FLUOW_AGENT_API_KEY = 'test-agent-key'
